name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install (local)
        run: pip install .

      - name: Install (pypi)
        run: pip install cosense

      - name: Uninstall
        run: pip uninstall -y cosense
